from __future__ import annotations

import uuid
from typing import List, Optional

from pydantic import BaseModel, Field


class DetectedIngredient(BaseModel):
    """Single ingredient detected on a fridge image."""

    name: str
    confidence: float = Field(ge=0.0, le=1.0)
    notes: Optional[str] = None


class ExtractIngredientsResult(BaseModel):
    """Structured response produced by the vision tool."""

    ingredients: List[DetectedIngredient]
    unsure_items: List[str] = Field(default_factory=list)
    spoiled_items: List[str] = Field(default_factory=list)


class SuggestionRequest(BaseModel):
    """Payload passed to the suggestion tool."""

    ingredients: List[str]
    servings: Optional[int] = Field(default=None, ge=1)
    dietary_preferences: Optional[List[str]] = None


# Internal schema for agent (without suggestion_id)
class AgentDishSummary(BaseModel):
    """Dish summary generated by agent without suggestion_id."""

    title: str
    short_description: str
    estimated_time_minutes: int = Field(ge=1)
    confidence: float = Field(ge=0.0, le=1.0)


# Internal schema for agent (without suggestion_id)
class AgentSuggestionsResult(BaseModel):
    """Structured output from the suggestion tool (agent version)."""

    dishes: List[AgentDishSummary]


# External schema for API (with suggestion_id added by backend)
class DishSummary(BaseModel):
    """Short representation of a suggested dish used on the mobile client."""

    suggestion_id: str
    title: str
    short_description: str
    estimated_time_minutes: int = Field(ge=1)
    confidence: float = Field(ge=0.0, le=1.0)


class SuggestionsResult(BaseModel):
    """Structured output from the suggestion tool (API version with IDs)."""

    dishes: List[DishSummary]

    @classmethod
    def from_agent_result(cls, agent_result: AgentSuggestionsResult) -> SuggestionsResult:
        """Convert agent result to API result by adding suggestion_id."""
        dishes_with_ids = [
            DishSummary(
                suggestion_id=str(uuid.uuid4()),
                title=dish.title,
                short_description=dish.short_description,
                estimated_time_minutes=dish.estimated_time_minutes,
                confidence=dish.confidence,
            )
            for dish in agent_result.dishes
        ]
        return cls(dishes=dishes_with_ids)


class RecipeRequest(BaseModel):
    """Payload describing which dish to expand into a recipe."""

    suggestion_id: str
    title: str
    context_summary: str
    servings: Optional[int] = None


class RecipeIngredient(BaseModel):
    """Single ingredient entry used in the final detailed recipe."""

    ingredient: str
    quantity: str
    preparation: Optional[str] = None


class RecipeStep(BaseModel):
    """Single preparation instruction."""

    number: int = Field(ge=1)
    instruction: str
    tip: Optional[str] = None


# Internal schema for agent (without suggestion_id)
class AgentRecipeResult(BaseModel):
    """Structured output returned by the recipe tool (agent version)."""

    title: str
    servings: Optional[int] = None
    prep_time_minutes: int = Field(ge=0)
    cook_time_minutes: int = Field(ge=0)
    ingredients: List[RecipeIngredient]
    steps: List[RecipeStep]
    equipment: List[str] = Field(default_factory=list)


# External schema for API (with suggestion_id added by backend)
class RecipeResult(BaseModel):
    """Structured output returned by the recipe tool (API version with ID)."""

    suggestion_id: str
    title: str
    servings: Optional[int] = None
    prep_time_minutes: int = Field(ge=0)
    cook_time_minutes: int = Field(ge=0)
    ingredients: List[RecipeIngredient]
    steps: List[RecipeStep]
    equipment: List[str] = Field(default_factory=list)

    @classmethod
    def from_agent_result(cls, agent_result: AgentRecipeResult, suggestion_id: str) -> RecipeResult:
        """Convert agent result to API result by adding suggestion_id from request."""
        return cls(
            suggestion_id=suggestion_id,
            title=agent_result.title,
            servings=agent_result.servings,
            prep_time_minutes=agent_result.prep_time_minutes,
            cook_time_minutes=agent_result.cook_time_minutes,
            ingredients=agent_result.ingredients,
            steps=agent_result.steps,
            equipment=agent_result.equipment,
        )


def build_recipe_request(
    summary: DishSummary,
    context_summary: str,
    servings: Optional[int],
) -> RecipeRequest:
    """Helper for creating recipe requests from suggestion selections."""

    return RecipeRequest(
        suggestion_id=summary.suggestion_id,
        title=summary.title,
        context_summary=context_summary,
        servings=servings,
    )
